### ISSUE TITLE
error SonyTV

### ISSUE THREAD

**Issue by kontur11** [n0rt0nthec4t/HAP-NodeJS-Accessories#1]
HAP-NodeJS starting...
Setup Sony Television 'Sony Bravia TV' on '10:08:B1:0D:0A:AF'
/home/dim/HAP-NodeJS/accessories/SonyTV_accessory.js:230
            var tempInputList = JSON.parse(response.body).result[0];
                                                                                                   ^

TypeError: Cannot read property '0' of undefined
    at SonyTVClass.__buildInputList (/home/dim/HAP-NodeJS/accessories/SonyTV_accessory.js:230:65)
    at SonyTVClass.addTelevison (/home/dim/HAP-NodeJS/accessories/SonyTV_accessory.js:60:14)
    at Object.<anonymous> (/home/dim/HAP-NodeJS/accessories/SonyTV_accessory.js:378:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by n0rt0nthec4t** [comment]
What model of Sony TV do you have? Code works on my Bravia x8500D

What does this command return?

curl -H "Content-Type: application/json"   -X POST -H "X-Auth-PSK: xxxx"   -d '{"id": 105, "method": "getCurrentExternalInputsStatus", "version": "1.1", "params": [""]}' http://x.x.x.x/sony/avContent

where xxxx is your PSK key and x.x.x.x is the IP of the TV

**Comment by kontur11** [comment]
Model KDL-60w605B
Command return: {"error":[12,"getCurrentExternalInputsStatus"],"id":105}

**Comment by kontur11** [comment]
Earned, changed "version": "1.1" to  "version": "1.0"
Thank You!!!
